import React, { useState } from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Home from "./Home";

export default function App() {
  let [language, SetLanguage] = useState("hi");
  let [search, setSearch] = useState("");
  let changeLanguage = (data) => {
    SetLanguage(data);
  };
  let changeSearch = (data) => {
    setSearch(data);
  };

  return (
    <BrowserRouter>
      <Navbar
        changeLanguage={changeLanguage}
        changeSearch={changeSearch}
      />
      <Routes>
        <Route
          path="/"
          element={
            <Home
              search={search}
              language={language}
              q="All"
            />
          }
        />
        <Route
          path="/All"
          element={
            <Home
              search={search}
              language={language}
              q="All"
            />
          }
        />
        <Route
          path="/Politics"
          element={
            <Home
              search={search}
              language={language}
              q="Politics"
            />
          }
        />
        <Route
          path="/Education"
          element={
            <Home
              search={search}
              language={language}
              q="Education"
            />
          }
        />
        <Route
          path="/Crime"
          element={
            <Home
              search={search}
              language={language}
              q="Crime"
            />
          }
        />
        <Route
          path="/Entertainment"
          element={
            <Home
              search={search}
              language={language}
              q="Entertainment"
            />
          }
        />
        <Route
          path="/Science"
          element={
            <Home
              search={search}
              language={language}
              q="Science"
            />
          }
        />
        <Route
          path="/Technology"
          element={
            <Home
              search={search}
              language={language}
              q="Technology"
            />
          }
        />
        <Route
          path="/Sports"
          element={
            <Home
              search={search}
              language={language}
              q="Sports"
            />
          }
        />
        <Route
          path="/Cricket"
          element={
            <Home
              search={search}
              language={language}
              q="Cricket"
            />
          }
        />
        <Route
          path="/Jokes"
          element={
            <Home
              search={search}
              language={language}
              q="Jokes"
            />
          }
        />
        <Route
          path="/Hindi"
          element={
            <Home
              search={search}
              language={language}
              q="Hindi"
            />
          }
        />
        <Route
          path="/English"
          element={
            <Home
              search={search}
              language={language}
              q="English"
            />
          }
        />
      </Routes>
      <Footer />
    </BrowserRouter>
  );
}
